"""add review

Revision ID: 250f1ef74bb7
Revises: 2e2469bf40e5
Create Date: 2024-03-13 13:45:47.131471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250f1ef74bb7'
down_revision = '2e2469bf40e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('item_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_reviews_items_id_items', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_item_id_items'), 'reviews', 'items', ['item_id'], ['id'])
    op.drop_column('reviews', 'items_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('items_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(op.f('fk_reviews_item_id_items'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_items_id_items', 'reviews', 'items', ['items_id'], ['id'])
    op.drop_column('reviews', 'item_id')
    # ### end Alembic commands ###
